// export const SEARCHVALUE='SEARCHVALUE';

export const SEARCHEDVALUE='SEARCHEDVALUE';
export const SUCCESSCONDITION='SUCCESSCONDITION';
export const FAILURECONDITION='FAILURECONDITION';

// export const SEARCHEDDATA='SEARCHEDDATA';